version: '3.7'
services:
  postgres:
    image: postgres:alpine3.20
    container_name: postgres
    restart: always
    ports:
      - 5444:5432
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: pass
